In [1]:
import pymongo
import pandas as pd
df = pd.read_csv("fraud.csv")
class MongoDBHandler:
    def __init__(self, host, port, database_name, collection_name):
        self.client = pymongo.MongoClient(f"mongodb://{host}:{port}")
        self.db = self.client[database_name]
        self.collection = self.db[collection_name]

    def insert_data(self, data):
        if isinstance(data, list):
            self.collection.insert_many(data)
        elif isinstance(data, dict):
            self.collection.insert_one(data)
        else:
            raise ValueError("Data should be a list or a dictionary.")

    def retrieve_data_as_dataframe(self, query=None):
        cursor = self.collection.find(query) if query else self.collection.find()
        data = list(cursor)
        df = pd.DataFrame(data)
        return df

    def close_connection(self):
        self.client.close()

if __name__ == "__main__":
    data = df.head(100).to_dict(orient="records")
    mongo_handler = MongoDBHandler(host="localhost", port=27017, database_name="fraud_detection_system", collection_name="data")
    mongo_handler.insert_data(data)
    mongo_handler = MongoDBHandler(host="localhost", port=27017, database_name="fraud_detection_system", collection_name="data")
    retrieved_data = mongo_handler.retrieve_data_as_dataframe()

# df.head(100) is used here for processing fast there are more than 6 million records in the csv file for faster processing speed only 100 were uploaded

In [2]:
retrieved_data

,_id,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,65397846ccf9eade9c88ba69,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.00,0.00,0,0
1,65397846ccf9eade9c88ba6a,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.00,0.00,0,0
2,65397846ccf9eade9c88ba6b,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.00,0.00,1,0
3,65397846ccf9eade9c88ba6c,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.00,0.00,1,0
4,65397846ccf9eade9c88ba6d,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.00,0.00,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
95,65397846ccf9eade9c88bac8,1,TRANSFER,710544.77,C835773569,0.0,0.00,C1359044626,738531.50,16518.36,0,0
96,65397846ccf9eade9c88bac9,1,TRANSFER,581294.26,C843299092,0.0,0.00,C1590550415,5195482.15,19169204.93,0,0
97,65397846ccf9eade9c88baca,1,TRANSFER,11996.58,C605982374,0.0,0.00,C1225616405,40255.00,0.00,0,0
98,65397846ccf9eade9c88bacb,1,PAYMENT,2875.10,C1412322831,15443.0,12567.90,M1651262695,0.00,0.00,0,0
99,65397846ccf9eade9c88bacc,1,PAYMENT,8586.98,C1305004711,3763.0,0.00,M494077446,0.00,0.00,0,0